GoogleCloudPlatform/opentelemetry-operations-java

exporters/trace/src/test/java/com/google/cloud/opentelemetry/trace/TraceTranslatorTest.java
=> Minor fixes in TraceTranslatorTest

exporters/trace/README.md
The readme hadn't been updated for a while, and especially after adding TraceConfiguration
I made some changes to the ReadMe, removing parts that were not really important like the imports, and added some snippets of TraceConfiguration
N/A
This commit is easier to read if you look at the rich text difference
=> Update Readme to include TraceConfiguration

build.gradle, examples/trace/src/main/java/com/google/cloud/opentelemetry/example/trace/TraceExporterExample.java, exporters/metrics/src/main/java/com.google.cloud.opentelemetry.metric/MetricExporter.java, exporters/metrics/src/main/java/com.google.cloud.opentelemetry.metric/MetricTranslator.java, exporters/metrics/src/test/java/com/google/cloud/opentelemetry/metric/EndToEndTest.java, exporters/metrics/src/test/java/com/google/cloud/opentelemetry/metric/FakeData.java, exporters/metrics/src/test/java/com/google/cloud/opentelemetry/metric/MetricExporterTest.java, exporters/metrics/src/test/java/com/google/cloud/opentelemetry/metric/MetricTranslatorTest.java, exporters/trace/src/main/java/com/google/cloud/opentelemetry/trace/TraceTranslator.java, exporters/trace/src/test/java/com/google/cloud/opentelemetry/trace/EndToEndTest.java, exporters/trace/src/test/java/com/google/cloud/opentelemetry/trace/TestSpanData.java, exporters/trace/src/test/java/com/google/cloud/opentelemetry/trace/TraceTranslatorTest.java
A lot of breaking changes from 0.7.0 to 0.9.1: https://github.com/open-telemetry/opentelemetry-java/releases
The instrumentation library is at 0.8.0 still.
=> Change dependency to version 0.9.1 of OpenTelemetry API & SDK

build.gradle, exporters/auto/src/main/java/com/google/cloud/opentelemetry/auto/GoogleCloudMetricExporterFactory.java, exporters/auto/src/main/java/com/google/cloud/opentelemetry/auto/GoogleCloudSpanExporterFactory.java
=> Using 0.9.0 spi change from open telemetry

build.gradle, exporters/trace/build.gradle, exporters/trace/src/main/java/com/google/cloud/opentelemetry/trace/TraceTranslator.java, exporters/trace/src/main/java/com/google/cloud/opentelemetry/trace/TraceVersions.java, exporters/trace/src/test/java/com/google/cloud/opentelemetry/trace/TraceTranslatorTest.java, exporters/trace/src/test/java/com/google/cloud/opentelemetry/trace/TraceVersionsTest.java
=> Dynamically look up version numbers for exporter

README.md, RELEASING.md, exporters/auto/README.md, exporters/metrics/README.md, exporters/trace/README.md
- Add latest maven release badges.
- Update docs for trace exporter for latest version
- Update RELASING.md for test-container build.
=> Update readmes for latest release.

build.gradle, cloudbuild-e2e-gce.yaml, cloudbuild-e2e-gke.yaml, cloudbuild-e2e-image.yaml, cloudbuild-e2e-local.yaml, e2e-test-server/README.md, e2e-test-server/build.gradle, e2e-test-server/gradle.properties, e2e-test-server/src/main/java/com/google/cloud/opentelemetry/endtoend/Constants.java, e2e-test-server/src/main/java/com/google/cloud/opentelemetry/endtoend/Request.java, e2e-test-server/src/main/java/com/google/cloud/opentelemetry/endtoend/Response.java, e2e-test-server/src/main/java/com/google/cloud/opentelemetry/endtoend/ScenarioHandler.java, e2e-test-server/src/main/java/com/google/cloud/opentelemetry/endtoend/ScenarioHandlerManager.java, e2e-test-server/src/main/java/com/google/cloud/opentelemetry/endtoend/Server.java, e2e-test-server/wait-for-image.sh, e2e.Dockerfile, settings.gradle
- Implementation of end-to-end integration testing spec for Trace exporter.
- Cloud Build integration for image + test runs against various environments.
- Scaffold framework for adding new test cases over time, including build + docker image.
=> Initial implementation of e2e tests

exporters/auto/README.md
Fixes #106 and gives users a warning about this module
=> Update java-auto-exporter readme

.dockerignore, cloudbuild-e2e-gce.yaml, cloudbuild-e2e-gke.yaml, cloudbuild-e2e-local.yaml, e2e-test-server/src/main/java/com/google/cloud/opentelemetry/endtoend/Constants.java, e2e-test-server/src/main/java/com/google/cloud/opentelemetry/endtoend/Response.java, e2e-test-server/src/main/java/com/google/cloud/opentelemetry/endtoend/ScenarioHandlerManager.java, e2e-test-server/src/main/java/com/google/cloud/opentelemetry/endtoend/Server.java
- Upgrade to newest test runner
- Send back trace ID to test runner
- Added dockerignore file to avoid adding everything to build context
=> e2e_tests: send back trace_id in response

build.gradle, e2e-test-server/build.gradle, e2e.Dockerfile, examples/autoconf/build.gradle, examples/metrics/build.gradle, examples/resource/build.gradle, examples/trace/build.gradle
Change tested against gradle 7.5.1
Fixes #108 
- Ran `gradle :e2e-test-server:build` successfully (against locally installed gradle version &rarr;  7.5.1)
- Updated Gradle version in the test-server image Dockerfile
- Successfully built Dockerfile - `docker build --tag=java_local:local --file=e2e.Dockerfile .`
=> Upgrade Gradle from v6.x to v7.x

e2e-test-server/src/main/java/com/google/cloud/opentelemetry/endtoend/PubSubPushServer.java
Adds required changes to enable existing tests to run in GAE environment.
=> Support GAE by handling readiness & liveliness checks

.allstar/allstar.yaml, .allstar/binary_artifacts.yaml, .allstar/branch_protection.yaml, .allstar/outside.yaml, .allstar/security.yaml
Adds configuration to opt-in this repository to [Allstar](https://github.com/ossf/allstar) for enforcing security policies.
- If the configuration here is successful, we should expect to see some automated issues created against this repository in a few hours after this PR is merged.
=> Repository opt-in to allstar

exporters/metrics/src/main/java/com/google/cloud/opentelemetry/metric/AggregateByLabelMetricTimeSeriesBuilder.java, exporters/metrics/src/main/java/com/google/cloud/opentelemetry/metric/GoogleCloudMetricExporter.java, exporters/metrics/src/main/java/com/google/cloud/opentelemetry/metric/MetricConfiguration.java, exporters/metrics/src/main/java/com/google/cloud/opentelemetry/metric/MetricTranslator.java, exporters/metrics/src/test/java/com/google/cloud/opentelemetry/metric/GoogleCloudMetricExporterTest.java, exporters/metrics/src/test/java/com/google/cloud/opentelemetry/metric/MetricTranslatorTest.java
=> Add prefix option to metrics exporter

build.gradle, cloudbuild-e2e-cloud-functions-gen2.yaml, cloudbuild-e2e-cloud-run.yaml, cloudbuild-e2e-gae.yaml, cloudbuild-e2e-gce.yaml, cloudbuild-e2e-gke.yaml, cloudbuild-e2e-local.yaml, detectors/resources/src/main/java/com/google/cloud/opentelemetry/detectors/GCPResource.java, detectors/resources/src/test/java/com/google/cloud/opentelemetry/detectors/GCPResourceTest.java, e2e-test-server/build.gradle, exporters/auto/build.gradle, shared/resourcemapping/build.gradle
Fixes #191 
Bump dependencies to fix the reported vulnerabilities. 
This needs to be done before addressing #188
=> Update dependencies to remove OSS vulnerabilities

propagators/gcp/README.md
=> Update README to add missing setup steps.

examples/trace/README.md, examples/trace/src/main/java/com/google/cloud/opentelemetry/example/trace/TraceExporterExample.java
=> Fix exporter-trace example & add README

exporters/trace/src/main/java/com/google/cloud/opentelemetry/trace/InternalTraceExporter.java, exporters/trace/src/main/java/com/google/cloud/opentelemetry/trace/TraceConfiguration.java, exporters/trace/src/main/java/com/google/cloud/opentelemetry/trace/TraceExporter.java
=> Fix documentation errors

gradle/wrapper/gradle-wrapper.properties
=> Upgrade to Gradle 7.6

propagators/gcp/src/main/java/com/google/cloud/opentelemetry/propagators/XCloudTraceContextPropagator.java
=> Make private static fields final

examples/instrumentation-quickstart/docker-compose.yaml, examples/instrumentation-quickstart/otel-collector-config.yaml, examples/instrumentation-quickstart/src/main/resources/logback.xml
Same as https://github.com/GoogleCloudPlatform/golang-samples/pull/3801
Tested manually
=> feat: simplify logging in instrumentation quickstart

examples/otlptrace/README.md, examples/otlptrace/src/main/java/com/google/cloud/opentelemetry/example/otlptrace/OTLPTraceExample.java
It is possible to generate traces using gRPC as well.
- `gradle run`
=> Add auth support for gRPC

shared/resourcemapping/src/main/java/com/google/cloud/opentelemetry/resource/ResourceTranslator.java
Minor refactor to the shared-resourcemapping module.
=> Make all AttributeMappings final

exporters/auto/README.md, exporters/metrics/README.md, exporters/trace/README.md, propagators/gcp/README.md
=> Udpate maven-badges to link to sonatype central

build.gradle, settings.gradle
Fixes https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/issues/361
I'm not particularly sure if this newer plugin version has any breaking changes. How can I test it?
=> Upgrade to latest nebula-release plugin to fix build

build.gradle, examples/metrics/build.gradle, examples/metrics/run_as_cloud-run-job.sh, examples/metrics/src/main/java/com/google/cloud/opentelemetry/example/metrics/MetricsExporterExample.java, examples/spring/build.gradle
Updates the current metrics example to add manual resource detection.
=> Update metrics example

exporters/auto/README.md, exporters/trace/README.md
=> Fix the sample code shown in README

propagators/gcp/src/main/java/com/google/cloud/opentelemetry/propagators/XCloudTraceContextPropagator.java
=> Remove obsolete TODO comment

examples/otlpmetrics-function/build.gradle, examples/otlpmetrics-function/collector-deployment/Dockerfile
Updates collector image and improves the `clean` task for cloud functions example.
Re: https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/pull/377#discussion_r1786657042
=> Update collector image

examples/autoinstrument/build.gradle, examples/autoinstrument/run_in_docker.sh
This change fixes the script that is used to build and run the application locally.
=> Fix local run for auto-instrumentation sample

examples/autoinstrument/README.md, examples/autoinstrument/build.gradle, examples/autoinstrument/deployment.yaml, examples/autoinstrument/run_in_cloud-run.sh
Updates auto-instrumentation sample to export traces using the OTLP exporters.
=> Update auto-instrumentation sample
