.gitignore
build.gradle
exporters/trace/build.gradle
exporters/trace/src/test/java/com/google/cloud/opentelemetry/trace/TraceExporterTest.java

**Context**
One of the issues in the repo right now is to add unit testing.
**Solution**
I added Junit4 instead of Junit5 because Junit5 is not compatible with java 8, which is defined in https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/blob/master/build.gradle. If you feel that we should be supporting Java8, let's have a conversation.
The current test is a constructor test, which isn't all that useful in itself but it shows that the testing dependency works and allows anybody who wants to write a unit test in the future to have a reference to go off of.
In addition, I added some elements to the `.gitignore` of things that I thought were best not to commit
**Test plan**
```sh
$ cd exporters/trace && gradle test
BUILD SUCCESSFUL in 4s
3 actionable tasks: 3 up-to-date …
```

Add unit testing dependency and starting unit test.

---

build.gradle

https://docs.google.com/document/d/1_-V36X4QfMGsrDfsmDniWkio9kdxr-8EI7Z9CSNmzCo/edit#
After discussion in this doc, we decided that supporting Java 8 as a minimum version is sufficient.
Update build.gradle from Java 7 to Java 8
```sh
$./gradlew build
$./gradlew test
```

Update version to Java 8

---

build.gradle
exporters/trace/src/main/java/com/google/cloud/opentelemetry/trace/TraceExporter.java
exporters/trace/src/main/java/com/google/cloud/opentelemetry/trace/TraceTranslator.java

I was working on writing and example class and was unable to use `OpenTelemetry.getTracer` I assumed that it was because we are using an earlier version of OpenTelemetry, so I decided to update it.
Update OpenTelemetry version to 0.6.0 in `build.gradle`, and then reflect the changes in `TraceExporter` and `TraceTranslator`.
The biggest changes were the types of `Attributes` being changed to `ReadableAttributes`, which seems to be an interface for a map, and `TimedEvents` being changed to an `Event`
Additionally, I ran the google java formatter on the file... which makes it much less readable. Is there an alternative formatter that we use?
```sh
$ gradle build && gradle test
BUILD SUCCESSFUL in 1s
4 actionable tasks: 4 up-to-date
BUILD SUCCESSFUL in 803ms
3 actionable tasks: 3 up-to-date …
```

Update OTEL version from 0.3.0 to current version 0.6.0

---

build.gradle
exporters/trace/build.gradle
exporters/trace/src/main/java/com/google/cloud/opentelemetry/trace/TraceConfiguration.java
exporters/trace/src/main/java/com/google/cloud/opentelemetry/trace/TraceExporter.java
exporters/trace/src/test/java/com/google/cloud/opentelemetry/trace/TraceConfigurationTest.java
exporters/trace/src/test/java/com/google/cloud/opentelemetry/trace/TraceExporterTest.java

Opencensus had a `StackdriverTraceConfiguration` file. This made it easy for customers to use the exporter while taking information from environment variables like project ID automatically. In addition, it abstracted away the details of making your own TraceServiceClient, which was not very clear how to do.
I created an abstract class which is generated using the @AutoValue annotation. This configuration should be able to be used to create a configuration, which will be able to be passed as an argument to the TraceExporter by customers.
The configuration contains many of the attributes important to customers, such as createTraceServiceStub.
In the future this will be integrated with the actual TraceExporter class for customers to make exporters.
```sh
$ gradle test
BUILD SUCCESSFUL in 1s …
```

Create a TraceConfiguration file and unit tests

---

build.gradle
exporters/trace/README.md
exporters/trace/build.gradle
exporters/trace/src/test/java/com/google/cloud/opentelemetry/trace/EndToEndTest.java
exporters/trace/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker

Add End to End Test ensuring that the spans generated by TraceTranslator's generateSpans() method and sent as a parameter to the batchWriteSpans() method are what we expect them to be.
EndToEndTest.java is run with JUnit 4; can also run using `./gradlew test` on the command line

Add Unit Test with mock TraceServiceClient

---

exporters/trace/src/main/java/com/google/cloud/opentelemetry/trace/TraceExporter.java
exporters/trace/src/test/java/com/google/cloud/opentelemetry/trace/EndToEndTest.java

PR 13 wasn't rebased before being merged, and some small errors popped up as a result. These are just three lines of quick fixes to get rid of those bugs so that EndToEndTest builds.

Fix Rebase Issue from PR #13

---

exporters/trace/src/main/java/com/google/cloud/opentelemetry/trace/TraceTranslator.java
exporters/trace/src/test/java/com/google/cloud/opentelemetry/trace/TraceTranslatorTest.java

Create unit tests to test all methods in TraceTranslator (except for generateSpans, as generateSpans is more or less just a combination of all the other methods anyways).
TraceTranslatorTest.java is run with JUnit 4; can also run using ./gradlew test on the command line

Add unit tests for TraceTranslator class

---

exporters/trace/src/main/java/com/google/cloud/opentelemetry/trace/TraceExporter.java

I think that it will be a common pattern to create TraceExporters using the default configuration, but right now it would take 2 lines of code to do so
Create a method for using the default configuration, saving developers a little bit of time.
```sh
$ gradle build && gradle test
```

Create a method for creating a trace exporter with default configuration

---

build.gradle
exporters/trace/build.gradle
exporters/trace/src/main/java/com/google/cloud/opentelemetry/trace/CloudTraceClient.java
exporters/trace/src/main/java/com/google/cloud/opentelemetry/trace/CloudTraceClientImpl.java
exporters/trace/src/main/java/com/google/cloud/opentelemetry/trace/MockCloudTraceClient.java
exporters/trace/src/main/java/com/google/cloud/opentelemetry/trace/MockTraceServiceClient.java
exporters/trace/src/main/java/com/google/cloud/opentelemetry/trace/TraceExporter.java
exporters/trace/src/main/java/com/google/cloud/opentelemetry/trace/TraceTranslator.java
exporters/trace/src/test/java/com/google/cloud/opentelemetry/trace/EndToEndTest.java
exporters/trace/src/test/java/com/google/cloud/opentelemetry/trace/TraceTranslatorTest.java
exporters/trace/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker

We'd like to integrate our [mock server](https://github.com/googleinterns/cloud-operations-api-mock) into the Java exporter to be used for integration testing.
Currently, the integration test just calls the mock server with the translated spans to verify that they follow the correct format and that the exporter has translated the spans properly. In the future, more tests can be added as needed.

Switch EndToEndTest to use mock server

---

exporters/trace/src/main/java/com/google/cloud/opentelemetry/trace/CloudTraceClient.java
exporters/trace/src/main/java/com/google/cloud/opentelemetry/trace/CloudTraceClientImpl.java
exporters/trace/src/main/java/com/google/cloud/opentelemetry/trace/MockCloudTraceClient.java
exporters/trace/src/main/java/com/google/cloud/opentelemetry/trace/TraceExporter.java

I found a shutdown method in TraceServiceClient, and we don't currently support shutdown.
Add a shutdown method to `CloudTraceClient`, and call it within `TraceExporter`
1. Run google java formatter
2. 
```sh
$ gradle build && gradle test
```

EZ: add shutdown method to 

---

.gitignore
examples/trace/build.gradle
examples/trace/settings.gradle
examples/trace/src/main/java/com/google/cloud/opentelemetry/example/trace/TraceExample.java
examples/trace/src/main/java/com/google/cloud/opentelemetry/example/trace/TraceExporterExample.java
settings.gradle

Right now customer don't have any way to see how to use our exporter
Create a TraceExample project with some sample code that customers can use. This involves a new gradle project with `build.gradle` and dependencies
Automatic tests
```sh
$ gradle test && gradle build
```
In addition I tested this project by deploying it to GKE using the following dockerfile
```dockerfile
FROM openjdk:8
VOLUME /tmp
RUN mkdir /application
COPY . /application
WORKDIR /application
RUN /application/gradlew build
RUN /application/gradlew clean build examples-trace:fatJar #if you use maven you can change to mvnw
RUN mv examples/trace/build/libs/examples-trace-0.0.0-SNAPSHOT-all.jar /application/app.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/application/app.jar"]
```
And list of …

Add an example project

---

examples/trace/src/main/java/com/google/cloud/opentelemetry/example/trace/TraceExporterExample.java

`SimpleSpanProcessor` shouldn't be used in production, so I'm changing it to `BatchSpanProcessor` in the example
Change the `SimpleSpanProcessor` to `BatchSpanProcessor` in the example
```sh
$ gradle build && gradle test
```
I didn't deploy it because that's a sizable amount of work, but I can deploy it if you think it needs to be tested.

Change SimpleSpanProcessor to BatchSpanProcessor in example

---

build.gradle

This allows `gradle uploadArchives` to be run to upload artefacts to https://oss.sonatype.org/content/repositories/snapshots/com/google/cloud/opentelemetry/.
Issue: #6

Configure gradle to publish to OSSRH

---

build.gradle

Project description must be added to close the staging repository, so that the deployment could be released from OSSRH to the Central Repository:

Add description to project

---

build.gradle

Bump master to the next version. 
Please don't merge this until the 0.7.0 deployment is released to the Central Repository.

Start 0.8.0 development cycle

---

build.gradle
exporters/metrics/build.gradle
exporters/metrics/src/main/java/com.google.cloud.opentelemetry.metric/MetricConfiguration.java
exporters/metrics/src/main/java/com.google.cloud.opentelemetry.metric/MetricExporter.java
exporters/metrics/src/main/java/com.google.cloud.opentelemetry.metric/MetricTranslator.java
exporters/trace/build.gradle
settings.gradle

This adds the metric exporter for Google cloud monitoring.
Unit tests here: https://github.com/zoercai/opentelemetry-operations-java/pull/1
End to end tests (WIP) here: https://github.com/zoercai/opentelemetry-operations-java/pull/2

Add metrics exporter

---

.circleci/config.yml
build.gradle
exporters/auto/README.md
exporters/auto/build.gradle
exporters/auto/src/main/java/com/google/cloud/opentelemetry/auto/GoogleCloudMetricExporterFactory.java
exporters/auto/src/main/java/com/google/cloud/opentelemetry/auto/GoogleCloudSpanExporterFactory.java
exporters/auto/src/main/resources/META-INF/services/io.opentelemetry.javaagent.tooling.exporter.SpanExporterFactory
settings.gradle

Building a jar isn't always an option for third party projects and tools. Leveraging auto-exporting is a really potent tool.
https://soundcloud.com/thundercat-official/overseas-feat-zack-fox?in=thundercat-official/sets/it-is-what-it-is-23611641

Init: Auto Instrumentation support

---

examples/trace/src/main/java/com/google/cloud/opentelemetry/example/trace/TraceExporterExample.java

- Use scopes
- Produce child spans
- Invoke `shutdown()` on exit to flush traces

Fix and improve the example code

---

build.gradle
exporters/metrics/src/main/java/com/google/cloud/opentelemetry/metric/MetricExporter.java
exporters/metrics/src/main/java/com/google/cloud/opentelemetry/metric/MetricTranslator.java
exporters/metrics/src/test/java/com/google/cloud/opentelemetry/metric/FakeData.java
exporters/metrics/src/test/java/com/google/cloud/opentelemetry/metric/MetricExporterTest.java
exporters/metrics/src/test/java/com/google/cloud/opentelemetry/metric/MetricTranslatorTest.java
exporters/trace/src/main/java/com/google/cloud/opentelemetry/trace/TraceTranslator.java
exporters/trace/src/test/java/com/google/cloud/opentelemetry/trace/TestSpanData.java

OpenTelemetry has API breaking changes from 0.11.0 onwards.  PR for updating Google Trace / Metrics to use OpenTelemetry 0.13.1

Resolving API breaking changes from 0.11.0 to 0.13.1

---

.github/header-checker-lint.yml
build.gradle
examples/metrics/build.gradle
examples/trace/build.gradle
exporters/auto/build.gradle
exporters/metrics/build.gradle
exporters/trace/build.gradle
get_mock_server.sh
settings.gradle

This seems to be redundant with spotlessCheck, but it should work with non-java files as well. I am adding this check to all ops repos.

add header checker lint config

---

.gitignore
RELEASING.md
build.gradle
exporters/auto/build.gradle
exporters/metrics/src/main/java/com/google/cloud/opentelemetry/metric/MetricDescriptorStrategy.java
exporters/trace/src/main/java/com/google/cloud/opentelemetry/trace/TraceTranslator.java
exporters/trace/src/test/java/com/google/cloud/opentelemetry/trace/TraceTranslatorTest.java
settings.gradle

This should dramatically improve our release instructions (in the near term) to just: 
`./gradlew {snapshot}` for snapshot builds and
`./gradlew -Prelease.veresion={version}` for release
Note: The release plugin will autoamtically create local git tags for you.
Long term, this should also be usable for a completed GHA-based publishing mechanism as used by OTel Java.
TL;DR; on Changes
- Leverage settings.gradle for plugin versioning in one location
- Add Nebula Release plugin to buld
- Move from deprecated `uploadArtifacts` task to `publish`
- Various gradle build jiggery-pokery
- Update all version strings to reflect the 0.14 java usage + prep for a 0.14.0 release of the exporters.

Update to use Nebula-Release plugin

---

RELEASING.md
build.gradle

We cut a candidate release with the new process and we have a (verbose) way to cut the first release.
We'll cut down steps in release process as we add more automation.

Update build + release docs for nebula plugin

---

build.gradle
detectors/resources/gradle.properties
exporters/auto/gradle.properties
exporters/metrics/gradle.properties
exporters/metrics/src/test/java/com/google/cloud/opentelemetry/metric/EndToEndTest.java
exporters/trace/gradle.properties
exporters/trace/src/test/java/com/google/cloud/opentelemetry/trace/EndToEndTest.java

- Add new mechanism to the build to look for `gradle.properties` file to determine publishing (as done in otel-java)
- Remove examples from publishing JARs onto maven central
- Mark Metrics + Auto instrumentation 'alpha' in accordance with community status.
- Mark Resource detection as not published (for now)
Output from my `publishToMavenLocal`:
```
$ ls ~/.m2/repository/com/google/cloud/opentelemetry/*
/home/joshuasuereth/.m2/repository/com/google/cloud/opentelemetry/exporter-auto:
0.14.0-alpha-SNAPSHOT  maven-metadata-local.xml
/home/joshuasuereth/.m2/repository/com/google/cloud/opentelemetry/exporter-metrics:
0.14.0-alpha-SNAPSHOT  maven-metadata-local.xml
/home/joshuasuereth/.m2/repository/com/google/cloud/opentelemetry/exporter-trace:
0.14.0-SNAPSHOT  maven-metadata-local.xml
```

Allow artifacts to opt-in to release or not.  

---

exporters/trace/src/main/java/com/google/cloud/opentelemetry/trace/TraceTranslator.java
exporters/trace/src/test/java/com/google/cloud/opentelemetry/trace/TraceTranslatorTest.java

- Update status code mapping to match internal specification for OTLP=>Cloud Trace
- Expand the tests for status code mapping to handle "non ok" statuses.

Fix #88 - Status code mapping and expanded tests.

---

settings.gradle

The Spring example appears to build again -- perhaps the JFrog server is back.

Restore Spring example

---

exporters/metrics/src/main/java/com/google/cloud/opentelemetry/metric/AggregateByLabelMetricTimeSeriesBuilder.java
exporters/metrics/src/main/java/com/google/cloud/opentelemetry/metric/MetricTranslator.java
exporters/metrics/src/main/java/com/google/cloud/opentelemetry/metric/ResourceTranslator.java
exporters/metrics/src/test/java/com/google/cloud/opentelemetry/metric/FakeData.java
exporters/metrics/src/test/java/com/google/cloud/opentelemetry/metric/MetricExporterTest.java
exporters/metrics/src/test/java/com/google/cloud/opentelemetry/metric/MetricTranslatorTest.java
exporters/metrics/src/test/java/com/google/cloud/opentelemetry/metric/ResourceTranslatorTest.java

This is a breaking change (and will need to be documented/major version bump), but we already have a major version bump coming for OTEL 1.16 change.
- Update resource mapping to be in-line w/ newly written collector resource mapping
- adds expanded tests for `aws_ec2_instance` and `generic_task`
- Never uses `global` resource
- Requires `cloud.platform` semconv attribute to use anything but generic_task.

Update resource mapping

---

build.gradle
detectors/resources/gradle.properties
e2e-test-server/build.gradle
e2e-test-server/src/main/java/com/google/cloud/opentelemetry/endtoend/ScenarioHandlerManager.java
exporters/auto/build.gradle
propagators/README.md
propagators/gcp/README.md
propagators/gcp/build.gradle
propagators/gcp/gradle.properties
propagators/gcp/src/main/java/com/google/cloud/opentelemetry/propagators/OneWayXCloudTraceConfigurablePropagatorProvider.java
propagators/gcp/src/main/java/com/google/cloud/opentelemetry/propagators/XCloudTraceConfigurablePropagatorProvider.java
propagators/gcp/src/main/java/com/google/cloud/opentelemetry/propagators/XCloudTraceContextPropagator.java
propagators/gcp/src/test/java/com/google/cloud/opentelemetry/propagators/AutoConfigureTest.java
propagators/gcp/src/test/java/com/google/cloud/opentelemetry/propagators/PropagatorTest.java
settings.gradle

- Pushes the `oneway` option as best-path for now
- Keeps similar implementation to Go/Python
Depends on / includes #145

Add X-Cloud-Trace-Context propagator support

---

exporters/metrics/src/main/java/com/google/cloud/opentelemetry/metric/MetricConfiguration.java

This matches the internal value in Cloud Monitoring and avoids
DEADLINE_EXCEEDED RPC errors.

Increase cloud monitoring client timeout to 12 s

---

exporters/trace/src/main/java/com/google/cloud/opentelemetry/trace/TraceExporter.java

This will help to identify spans generated by OTel and measure adoption of new versions.

Set user agent header

---

cloudbuild-e2e-cloud-run.yaml
cloudbuild-e2e-gce.yaml
cloudbuild-e2e-gke.yaml
cloudbuild-e2e-local.yaml

Updates the test runner image version so that the cloud run tests can be run without being skipped. 
The latest image for test runner has the required Monitored Resource mappings for Cloud Run resource detection.
Fixes #169

Update the test runner image version

---

.allstar/allstar.yaml
.allstar/binary_artifacts.yaml
.allstar/branch_protection.yaml
.allstar/outside.yaml
.allstar/security.yaml

The configurations work, but they may turn out to be duplicates since they need to be enabled at the org level. 
Due to this configuration, [these issues](https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/issues?q=is%3Aissue+label%3Aallstar+) were auto-generated. 
Removing these configs from the repo level for now. The auto generated issues will be closed after this PR is merged.

Remove repo level allstar configs

---

e2e-test-server/src/main/java/com/google/cloud/opentelemetry/endtoend/ScenarioHandlerManager.java
examples/trace/src/main/java/com/google/cloud/opentelemetry/example/trace/TraceExporterExample.java
exporters/trace/src/main/java/com/google/cloud/opentelemetry/trace/TraceExporter.java
exporters/trace/src/test/java/com/google/cloud/opentelemetry/trace/EndToEndTest.java
exporters/trace/src/test/java/com/google/cloud/opentelemetry/trace/TraceExporterTest.java

- Replacing the usages of concrete type `TraceExporter` with interface type `SpanExporter` for public methods in `TraceExporter` class.
This change should help with the future work of adding a Lazy initialized / Deferred trace exporter.

Replaced concrete type TraceExporter with interface type SpanExporter

---

exporters/trace/build.gradle

Removes shadow plugin since it is not required and not adding any additional benefit.

Remove shadow plugin from exporter-trace module

---

cloudbuild-e2e-cloud-functions-gen2.yaml

This is to improve the build-times as 'shadowJar' generates shadowJars for all sub-projects which is expensive and not required here.

Improve build time for e2e-test-server

---

build.gradle
exporters/auto/build.gradle

This updates the exporter-auto build config to be able to generate both - shaded and non-shaded versions of the dependency. 
- `./gradlew build` generates non-shaded version. (slim-JAR)
- `./gradlew shadowJar` generates uberJar with shaded (relocated) dependencies. 
- Ran the `autoconf` and `autoinstrument` examples with the updated JARs - both ran successfully. 
- `autoinstrument` - Traces are being generated; Metrics have a known issue -  #149
- The maven publish plugin would have to be configured to release both artifacts. [TODO]
- The conscrypt plugin is intentionally not shaded - see [this comment](https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/issues/161#issuecomment-1478831626).
- The source classes are also erroneously relocated to the shadow prefix, i.e. …

Relocate dependencies in the generated shadowJar

---

detectors/resources/build.gradle
detectors/resources/src/test/java/com/google/cloud/opentelemetry/detectors/GCPResourceTest.java

fixes #216 
The unit test to verify that empty attributes are returned in non GCP environment, assumed that the test environment would be non GCE. This led to failures when running on GCE VMs.

Make GCPResourceTest environment agnostic

---

examples/autoconf/build.gradle
examples/autoconf/job.yaml

The OTel autoconfigure module was missing configuration parameters and the GKE container was missing required environment variables to publish Cloud monitoring metrics.

Fix autoconf example

---

build.gradle
examples/resource/build.gradle

Autoconfigure SDK extension is used but has not been configured. In this case, the default otlp exporter must be present on the classpath.
- Ran the resource detection example successfully.

Add missing otlp exporter dependency

---

examples/autoinstrument/README.md
examples/autoinstrument/build.gradle
examples/autoinstrument/deployment.yaml

The added environmnet variables are required for resource detection in GKE environment. The absence of these variables cause failure to publish metrics.

Add required env variables for publishing metrics

---

exporters/auto/build.gradle
exporters/auto/gradle.properties

Supports #215 
Currently, if `gradle.properties` have `shadowed` property set to true, then only shadowed variant is published, this change also configures the maven-publish plugin to publish normal Jar along with the shadow-jar. 
The `artifactId` is currently set to be the `archivesBaseName` which based on current configuration for auto-exporter should contain the suffix - `shaded`.
- Ran `./gradlew clean build`
- Ran `./gradlew publishToMavenLocal` & verified that the `.m2` repository contained both - shaded and non-shaded JARs.
Below is the tree structure of the generated artifacts (from local `.m2` repo)
```
exporter-auto/
├── 0.1.0-alpha-SNAPSHOT
│   ├── exporter-auto-0.1.0-alpha-SNAPSHOT.jar
│   ├── exporter-auto-0.1.0-alpha-SNAPSHOT-javadoc.jar
│   ├── …
```

Configures auto-exporter to publish shaded and non-shaded variants

---

exporters/metrics/build.gradle
exporters/trace/build.gradle
shared/resourcemapping/build.gradle

The missing dependency declarations result in errors in the release tasks - pointing to possibility of incorrect result depending on order in which these tasks execute.
The release tasks are skipped during normal :build jobs so build passes, but the artifacts snapshot generation for release fails.
Supports #215

Adds dependency declarations to order tasks

---

shared/resourcemapping/build.gradle

Adds missing dependency declaration for task `signMavenPublication` for shared-resourcemapping module. 
- Verified `./gradlew clean build`
- Verified `./gradlew snapshot` - is now passing ✅

Declares explicit dependency for signMavenPublication

---

examples/autoinstrument/README.md
examples/autoinstrument/run_in_docker.sh

This just adds a convenience script that allows users to run auto-instrument example in a local docker container instead of running on GKE.

Add script to run example in docker container

---

build.gradle

This makes sure that the POM generated for `exporter-auto` has correct dependency versions. The current POM is broken, which makes the non-shaded variant difficult to use. 
We use release qualifiers which are appended to the version names, these qualifiers seem to be stripped away during versionMapping phase - [v0.25.0-alpha POM](https://search.maven.org/artifact/com.google.cloud.opentelemetry/exporter-auto/0.25.0-alpha/jar). 
The new generated POM - *from the staging sonatype repository*
```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
<modelVersion>4.0.0</modelVersion>
<groupId>com.google.cloud.opentelemetry</groupId> …
```

Fixes broken pom by removing versionMapping

---

examples/metrics/README.md
examples/metrics/run_as_cloud-run-job.sh

Enhances the example by adding a README and by providing a convenience script to run the example as a cloud-run-job.

Enable metrics-exporter example to run as cloud run job

---

.github/header-checker-lint.yml
build.gradle
buildscripts/spotless.license.dockerfile
e2e.Dockerfile

See https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/issues/144. This was mostly done in #230 but one got through.
Ran
```sh
perl -i -pe 's/Copyright (\d+) Google$/Copyright $1 Google LLC/g' $(git ls-files)
```

Update copyright from "Google" -> "Google LLC"

---

exporters/metrics/src/main/java/com/google/cloud/opentelemetry/metric/MetricTranslator.java

Using Java Paths class to combine string leads to different path-separators depending on the OS of the machine code runs on. For metric names, only the linux path-separators are valid, so hardcoding this.
- Tested this change on a windows machine by running the [metrics example](https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/tree/main/examples/metrics) and ensuring that exported metrics appear in GCP.
- Fix #252

Hardcode path separator used for metric type

---

cloudbuild-e2e-cloud-functions-gen2.yaml
cloudbuild-e2e-cloud-run.yaml
cloudbuild-e2e-gae.yaml
cloudbuild-e2e-gce.yaml
cloudbuild-e2e-gke.yaml
cloudbuild-e2e-local.yaml
detectors/resources/src/main/java/com/google/cloud/opentelemetry/detectors/AttributesExtractorUtil.java
detectors/resources/src/main/java/com/google/cloud/opentelemetry/detectors/GCPResource.java
detectors/resources/src/test/java/com/google/cloud/opentelemetry/detectors/GCPResourceTest.java
shared/resourcemapping/src/main/java/com/google/cloud/opentelemetry/resource/ResourceTranslator.java

Context: https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/issues/679
This also bumps the e2e test image to pick up the validation for faas.instance.

Use faas.instance instead of faas.id in resource detection and mapping

---

e2e-test-server/src/main/java/com/google/cloud/opentelemetry/endtoend/ScenarioHandlerManager.java

Fixes https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/issues/268
It uses a synchronous export of spans to ensure spans are delivered before cloud functions reclaims the CPU.

Fix cloudfunctions test

---

build.gradle

When trying to build the project with JDK 17 and `gradle assemble`, I get the following error message:
```
> You are running Spotless on JVM 17. This requires google-java-format of at least 1.10.0 (you are using 1.9).
```
Just upgrading the google java format to the next version as instructed works.

upgrade google java format for jdk 17

---

build.gradle
detectors/resources/src/main/java/com/google/cloud/opentelemetry/detectors/AttributesExtractorUtil.java
detectors/resources/src/main/java/com/google/cloud/opentelemetry/detectors/GCPResource.java
detectors/resources/src/test/java/com/google/cloud/opentelemetry/detectors/GCPResourceTest.java
e2e-test-server/build.gradle
e2e-test-server/src/main/java/com/google/cloud/opentelemetry/endtoend/ScenarioHandlerManager.java
examples/resource/build.gradle
examples/resource/src/main/java/com/google/cloud/opentelemetry/example/resource/ResourceExample.java
exporters/metrics/src/test/java/com/google/cloud/opentelemetry/metric/FakeData.java
exporters/trace/src/main/java/com/google/cloud/opentelemetry/trace/TraceVersions.java
exporters/trace/src/test/java/com/google/cloud/opentelemetry/trace/TraceTranslatorTest.java
propagators/gcp/src/test/java/com/google/cloud/opentelemetry/propagators/AutoConfigureTest.java
shared/resourcemapping/src/main/java/com/google/cloud/opentelemetry/resource/ResourceTranslator.java
shared/resourcemapping/src/test/java/com/google/cloud/opentelemetry/resource/ResourceTranslatorTest.java

There were breaking changes introduced in the latest upstream OTel [releases](https://github.com/open-telemetry/opentelemetry-java/releases), causing the latest auto-instrumentation agent to be incompatible with GCP exporters.
This PR addresses those breaking changes.
fixes #263

Update OTel dependencies

---

shared/resourcemapping/src/main/java/com/google/cloud/opentelemetry/resource/ResourceTranslator.java
shared/resourcemapping/src/test/java/com/google/cloud/opentelemetry/resource/ResourceTranslatorTest.java

Fixes #265 
This PR: 
- adds missing faas.* attributes mappings for `generic_task`.
- adds missing resource mapping for `generic_node`.

Update mappings for generic_task and generic_node

---

detectors/resources/build.gradle

This PR makes the resource detector Java 8 compatible. This is to support #266.
- Used the GCP Detector jar built from this change in a Java 8 application (running in a docker container) to successfully detect resources. The Java 8 application was similar to [resource-example](examples/resource/src/main/java/com/google/cloud/opentelemetry/example/resource/ResourceExample.java) in the current repo.
- Used the `javap` tool to check the major version with which the classes was compiled - 
```sh
javap -v javap -v detectors/resources/build/classes/java/main/com/google/cloud/opentelemetry/detectors/*.class | grep major
```
Output - 
```sh
major version: 52
major version: 52
major version: 52
major version: 52
```
Indicates all classes within resource detector are Java 8 compatible.
Other …

Make resource-detector compatible with Java 8

---

.github/header-checker-lint.yml
buildscripts/spotless.license.dockerfile
buildscripts/spotless.license.gradle
buildscripts/spotless.license.java
buildscripts/spotless.license.shell
buildscripts/spotless.license.yaml

The current config forces us to update the static year in the license header config(s) along with every year change - also causes the year in all files to update (rather than only updating the year in newly added files).
For details see [spotless documentation for license headers](https://github.com/diffplug/spotless/blob/main/plugin-gradle/README.md#license-header).

Fixed spotless config for copyright year

---

exporters/auto/README.md

Add download link template for exporter-auto shaded JAR file for easier access.

Update readme to include download link for exporter auto

---

detectors/resources-support/gradle.properties

Enables gradle `publishing` task to run on the `detetctor-resources-support` module.

Enable resource-detection-support library for release

---

examples/instrumentation-quickstart/.dockerignore
examples/instrumentation-quickstart/.gitignore
examples/instrumentation-quickstart/.mvn/wrapper/maven-wrapper.properties
examples/instrumentation-quickstart/Dockerfile
examples/instrumentation-quickstart/README.md
examples/instrumentation-quickstart/docker-compose.adc.yaml
examples/instrumentation-quickstart/docker-compose.yaml
examples/instrumentation-quickstart/mvnw
examples/instrumentation-quickstart/mvnw.cmd
examples/instrumentation-quickstart/otel-collector-config.yaml
examples/instrumentation-quickstart/pom.xml
examples/instrumentation-quickstart/src/main/java/com/example/demo/DemoApplication.java
examples/instrumentation-quickstart/src/main/java/com/example/demo/MultiController.java
examples/instrumentation-quickstart/src/main/java/com/example/demo/SingleController.java
examples/instrumentation-quickstart/src/main/resources/logback.xml
examples/instrumentation-quickstart/src/test/java/com/example/demo/DemoApplicationTests.java
examples/instrumentation-quickstart/src/test/java/com/example/demo/DockerComposeTestsIT.java
examples/instrumentation-quickstart/src/test/resources/logback-test.xml

Copied directly from https://github.com/GoogleCloudPlatform/java-docs-samples/tree/main/opentelemetry/spring-boot-instrumentation–no other changes were made. I will port this over to gradle in a separate PR.
Please ignore header check, we should preserve the original date from the other repo

Copy instrumentation quickstart out of java-docs-samples

---

examples/instrumentation-quickstart/README.md
examples/instrumentation-quickstart/docker-compose.creds.yaml
examples/instrumentation-quickstart/otel-collector-config.yaml
examples/instrumentation-quickstart/src/test/java/com/example/demo/DockerComposeTestsIT.java

Cloud Trace API requires a quota project. This change passes through `GOOGLE_CLOUD_QUOTA_PROJECT` environment variable, which Cloud Shell has automatically set. This is better than doing the resource project override and works better off Cloud Shell. I also renamed the file to reflect that it works with any credentials file, including SA keys.
Equivalent of https://github.com/GoogleCloudPlatform/golang-samples/pull/3760 from the Go repo

Quota project fix

---

examples/instrumentation-quickstart/pom.xml
examples/instrumentation-quickstart/src/test/java/com/example/demo/DockerComposeTestsIT.java

This is a port over of https://github.com/GoogleCloudPlatform/java-docs-samples/pull/8984/ to this repo.
The breakage was actually caused by upgrading logstash-encoder to 7.4 because [it does not support logback versions prior to 1.3.0](https://github.com/logfellow/logstash-logback-encoder#:~:text=Support%20for%20logback%20versions%20prior%20to%201.3.0%20was%20removed%20in%20logstash%2Dlogback%2Dencoder%207.4.). Spring Boot 2 uses an [older logback version](https://docs.spring.io/spring-boot/docs/2.7.18/reference/html/dependency-versions.html).

Use logstash-logback-encoder version that works with spring boot 2

---

.github/workflows/pr-build.yml
examples/instrumentation-quickstart/.dockerignore
examples/instrumentation-quickstart/build.gradle
examples/instrumentation-quickstart/cloudbuild-integration.yaml
examples/instrumentation-quickstart/docker-compose.test.yaml
examples/instrumentation-quickstart/docker-compose.yaml
examples/instrumentation-quickstart/src/test/java/com/example/demo/DockerComposeTestsIT.java

Adds GHA matrices for testing/style checking and Cloud Build trigger for running integration test. The Cloud Build trigger is only run when files under `examples/instrumentation-quickstart` are touched.

Add CI for examples/instrumentation-quickstart

---

.github/workflows/pr-build.yml

Leaving the java-version parameterized so we can easily add tests against multiple Java versions in the future (https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/issues/294).

Test against java 11

---

build.gradle
examples/otlptrace/README.md
examples/otlptrace/build.gradle
examples/otlptrace/src/main/java/com/google/cloud/opentelemetry/example/otlptrace/OTLPTraceExample.java
settings.gradle

Cobbled this together following docs from:
* https://opentelemetry.io/docs/languages/java/exporters/
* https://github.com/googleapis/google-auth-library-java
* https://github.com/googleapis/google-auth-library-java/blob/main/samples/snippets/src/main/java/AuthenticateExplicit.java
* https://cloud.google.com/java/docs/reference/google-auth-library/latest/com.google.auth.oauth2.GoogleCredentials
* https://javadoc.io/static/io.opentelemetry/opentelemetry-exporter-otlp-http-trace/1.14.0/io/opentelemetry/exporter/otlp/http/trace/OtlpHttpSpanExporterBuilder.html
Same idea as https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/pull/800, https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/pull/307, and https://github.com/GoogleCloudPlatform/opentelemetry-operation …

Add OTLP trace with ADC example

---

exporters/auto/README.md

Updates the javaagent path sample to reflect the updated naming in upstream. 
The existing sample naming in the doc seemed to be causing minor confusion as seen in #303 .
Also updates the import samples to use the latest dependency version.

Update auto-exporter readme

---

examples/trace/build.gradle
examples/trace/src/main/java/com/google/cloud/opentelemetry/example/trace/TraceExporterExample.java
examples/trace/src/test/java/com/google/cloud/opentelemetry/example/trace/TraceExporterExampleTest.java

Adding a unit test demonstrating the use of [InMemorySpanExporter](https://github.com/open-telemetry/opentelemetry-java/blob/f83c020d4d2a11f16be8af739790718bb3413cba/sdk/testing/src/main/java/io/opentelemetry/sdk/testing/exporter/InMemorySpanExporter.java) to verify spans generated by the application.
- Ran the sample and verified the attributes presence in the generated span.
- The newly added test passed.
Re: #277

Add tests to verify OTel integration using in-memory exporter

---

examples/instrumentation-quickstart/docker-compose.yaml

I forgot to add this line in https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/pull/286. It passes through the standard quota project envvar which makes the sample work seamlessly on Cloud Shell

Add missing GOOGLE_CLOUD_QUOTA_PROJECT environment variable to compose file

---

examples/instrumentation-quickstart/Dockerfile

The `opentelemetry_instrumentation_agent_dockerfile` region tag is more general and can be referenced across different languages. I am using the same one for JS in https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/pull/687
I have "pinned" the docs build to existing version to prevent breaking links in the docs.

Update instrumentation quickstart to new region tag name

---

exporters/metrics/build.gradle
exporters/metrics/src/main/java/com/google/cloud/opentelemetry/metric/AggregateByLabelMetricTimeSeriesBuilder.java
exporters/metrics/src/main/java/com/google/cloud/opentelemetry/metric/InternalMetricExporter.java
exporters/metrics/src/main/java/com/google/cloud/opentelemetry/metric/MetricConfiguration.java
exporters/metrics/src/main/java/com/google/cloud/opentelemetry/metric/MetricTranslator.java
exporters/metrics/src/test/java/com/google/cloud/opentelemetry/metric/FakeData.java
exporters/metrics/src/test/java/com/google/cloud/opentelemetry/metric/GoogleCloudMetricExporterTest.java
exporters/metrics/src/test/java/com/google/cloud/opentelemetry/metric/MetricTranslatorTest.java

- Adds user configurable option to attach `service.name`, `service.namespace` and `service.id` resource attributes to metric labels. 
- This can be disabled by passing the provided `NO_RESOURCE_ATTRIBUTES` as the resource filter to the `MetricConfiguration` object.
- The default metric configuration has been changed to use the `DEFAULT_RESOURCE_ATTRIBUTES_FILTER`. 
Note: This is similar to how the [Google Cloud Monitoring go exporter works](https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/2be0414d564ce62759e2da63615b27103ab950d3/exporter/metric/option.go#L114).
- When running the auto-instrumentation-example, `service_name` appears under metric labels on GCP console with the expected value.
- When running the metric export example, `service_name` appears with …

Add resource attributes as metric labels

---

examples/autoconf/README.md
examples/autoconf/build.gradle
examples/resource/README.md
examples/resource/build.gradle
examples/resource/src/main/java/com/google/cloud/opentelemetry/example/resource/ResourceExample.java

- Updates Readme to add missing prerequisites.
- Attempts to clarify the intention of the resource example.
Once this is merged, the [README for the upstream GCP Detector](https://github.com/open-telemetry/opentelemetry-java-contrib/tree/main/gcp-resources) can be updated to clarify that recommended way for resource detection is via `autoconfiguration` and we can link to this example for further clarification.

Update resource detection sample

---

exporters/metrics/src/main/java/com/google/cloud/opentelemetry/metric/MetricConfiguration.java
exporters/metrics/src/test/java/com/google/cloud/opentelemetry/metric/MetricConfigurationTest.java

The recently added `setResourceAttributesFilter` in #314 was not publicly exposed on `MetricConfiguration`. 
This PR makes the setting the resource attribute filter public and adds missing tests.
- `./gradlew test`

Make setResourceAttributesFilter public

---

exporters/metrics/src/main/java/com/google/cloud/opentelemetry/metric/CloudMetricClient.java
exporters/metrics/src/main/java/com/google/cloud/opentelemetry/metric/CloudMetricClientImpl.java
exporters/metrics/src/main/java/com/google/cloud/opentelemetry/metric/InternalMetricExporter.java
exporters/metrics/src/main/java/com/google/cloud/opentelemetry/metric/MetricConfiguration.java
exporters/metrics/src/test/java/com/google/cloud/opentelemetry/metric/FakeData.java
exporters/metrics/src/test/java/com/google/cloud/opentelemetry/metric/GoogleCloudMetricExporterTest.java
exporters/metrics/src/test/java/com/google/cloud/opentelemetry/metric/MetricConfigurationTest.java

Add support for createServiceTimeSeries

---

detectors/resources/gradle.properties

The GCP Resource Detector has been moved to the [upstream contrib repo](https://github.com/open-telemetry/opentelemetry-java-contrib/tree/main/gcp-resources). 
This PR removes it from the general release cycle. The source code might be deleted from here in the future releases.

Disable release for gcp-resource-detector

---

README.md
detectors/resources-support/README.md

The badges are generated using https://shields.io.
[search.maven.org](http://search.maven.org/) is [being retired](https://central.sonatype.org/faq/what-happened-to-search-maven-org/) and is being replaced with Sonatype central. [seach.maven.org](https://search.maven.org)'s index is not being refreshed very consistently. For instance currently, the [last index refresh](https://search.maven.org/stats) was done on 3rd April - which is why it doesn't always show the latest version.
We currently use https://github.com/softwaremill/maven-badges to show the badges on our README (for our java-ops repo), it is backed by [search.maven.org](http://search.maven.org/).
Switching to shields.io allows us to generate dynamic badges which can be pointed to sonatype central servers to fetch the latest …

Update maven-badges to link to sonatype central

---

detectors/resources-support/src/main/java/com/google/cloud/opentelemetry/detection/GCPMetadataConfig.java

Switching to concurrentHashMap since the performance impact is minimal and we gain thread-safety when accessing/updating the attribute cache.

Switch to ConcurrentMap for thread-safety

---

examples/instrumentation-quickstart/src/main/resources/log4j2.xml

If this field is not set to `true`, Cloud Logging will grey-out the "View trace details" feature. This is a better workaround until I have a real fix for #331

Always output logging.googleapis.com/trace_sampled as true

---

examples/autoinstrument/build.gradle
propagators/gcp/README.md

otel.java.experimental.extesion JVM Flag was updated to otel.java.extension since Release v1.30.0
- `./gradlew clean build`
- Ran the auto-instrumentation sample to ensure that traces and metrics show up in GCP console.
Fixes #335

Update JVM flag otel.java.experimental.extension

---

detectors/resources-support/src/test/java/com/google/cloud/opentelemetry/detection/GCPPlatformDetectorTest.java

This PR just adds a test case to verify that zone detection on GAE standard is working.
On GAE standard, the metadata server provides zone strings like `projects/233510669999/zones/us15`. The resource detector should return `us15` in this case.

Add test case for zone resource detection on GAE standard

---

shared/resourcemapping/src/main/java/com/google/cloud/opentelemetry/resource/ResourceTranslator.java
shared/resourcemapping/src/test/java/com/google/cloud/opentelemetry/resource/ResourceTranslatorTest.java

Fix #340 's bug.
I made bellow changes.
- `shared/resourcemapping/src/test/java/com/google/cloud/opentelemetry/resource/ResourceTranslatorTest.java` All or most of test case's  `CLOUD_PROVIDER` are `GCP`.  But I think it is not correct. It should map bellow.
- When `GCP_KUBERNETES_ENGINE ` then `GCP`
- When `AZURE_AKS` then `AZURE`
- When `AWS_EKS` then `AWS`
- When null then no key and value. (not cloud)
- This mapping follows Go's repository. Like here.  https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/pull/683/files#diff-68a9a0e83deda8fe72338c49bcedd7da9b1633f67d40473059117d9db844529aR130-R343
- **So I fixed about `CLOUD_PROVIDER` in most of cases.**
- `shared/resourcemapping/src/test/java/com/google/cloud/opentelemetry/resource/ResourceTranslatorTest.java` All or …

Fix #340 bug

---

exporters/metrics/src/main/java/com/google/cloud/opentelemetry/metric/AggregateByLabelMetricTimeSeriesBuilder.java
exporters/metrics/src/main/java/com/google/cloud/opentelemetry/metric/InternalMetricExporter.java
exporters/metrics/src/main/java/com/google/cloud/opentelemetry/metric/MetricConfiguration.java
exporters/metrics/src/main/java/com/google/cloud/opentelemetry/metric/MonitoredResourceDescription.java
exporters/metrics/src/main/java/com/google/cloud/opentelemetry/metric/MonitoredResourceMapping.java
exporters/metrics/src/main/java/com/google/cloud/opentelemetry/metric/ResourceTranslator.java
exporters/metrics/src/test/java/com/google/cloud/opentelemetry/metric/FakeData.java
exporters/metrics/src/test/java/com/google/cloud/opentelemetry/metric/GoogleCloudMetricExporterTest.java
exporters/metrics/src/test/java/com/google/cloud/opentelemetry/metric/MetricConfigurationTest.java

Provides a configuration option for the metrics exporter allowing users to specify mappings for custom MonitoredResource type. 
The mapping logic for the custom MR type is activated based on the presence of `gcp.resource_type` resource attribute in the underlying OpenTelemetry resource.
Some methods were marked with `@Deprecated` but no breaking changes were made in this PR. 
```java
// MetricConfiguration object for the metrics exporter - 
MetricConfiguration configuration =
MetricConfiguration.builder()
.setProjectId(PROJECT_ID)
.setCredentials(CREDENTIALS)
.setResourceAttributesFilter(allowAllPredicate)
.setMonitoredResourceDescription(
new MonitoredResourceDescription(
"custom_mr", Set.of("instance_id", "api", "host_id")))
.setUseServiceTimeSeries(true)
.build();
// If the OTel …
```

Add support for custom MR mappings

---

propagators/gcp/src/main/java/com/google/cloud/opentelemetry/propagators/XCloudTraceContextPropagator.java
propagators/gcp/src/test/java/com/google/cloud/opentelemetry/propagators/PropagatorTest.java

Hello guys,
I've observed that Cloud load balancing sends requests with `x-cloud-trace-context` that lack `o=<sampled>` to the backend service.
This is causing the propagator not properly to propagate the trace context.
I addressed this issue by making the trace flag optional.
Could someone look over this?
Ref: https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/issues/167

Make the trace flags optional when parsing x-cloud-trace-context

---

RELEASING.md

Maven central recently switched to a user-token based authentication system which requires an update to how releases should be made.

Update instructions to reflect recent auth changes

---

examples/metrics/README.md
examples/metrics/src/main/java/com/google/cloud/opentelemetry/example/metrics/MetricsExporterExample.java
exporters/metrics/src/main/java/com/google/cloud/opentelemetry/metric/InternalMetricExporter.java
exporters/metrics/src/main/java/com/google/cloud/opentelemetry/metric/MetricConfiguration.java
exporters/metrics/src/test/java/com/google/cloud/opentelemetry/metric/GoogleCloudMetricExporterTest.java

This PR adds a configuration option to the `MetricConfiguration` that allows the user to configure the underlying instance of `MetricServiceClient` which is used by the exporter to interact with the Cloud Monitoring API.
This feature is intended for advanced use-cases only.
- Added unit tests pass.
- Updated the metrics sample to demonstrate a use-case for the `setMetricServiceSettings` function.
fixes. #149

Expose option to provide MetricServiceSettings in MetricConfiguration

---

examples/metrics/src/main/java/com/google/cloud/opentelemetry/example/metrics/MetricsExporterExample.java
exporters/metrics/src/main/java/com/google/cloud/opentelemetry/metric/AggregateByLabelMetricTimeSeriesBuilder.java
exporters/metrics/src/main/java/com/google/cloud/opentelemetry/metric/InternalMetricExporter.java
exporters/metrics/src/main/java/com/google/cloud/opentelemetry/metric/MetricConfiguration.java
exporters/metrics/src/test/java/com/google/cloud/opentelemetry/metric/GoogleCloudMetricExporterTest.java

This PR adds a config option - `setInstrumentationLibraryLabelsEnabled(boolean)` that allows the user to configure the exporter to not attach the instrumentation library labels as metric attributes during export.
By default these labels are attached automatically by the exporter during export time.
- Added unit tests to verify the behavior.
- Tested the config option through the metrics example. 
fixes #357

Add config option to disable attaching InstrumentationLibrary labels

---

cloudbuild-e2e-cloud-functions-gen2.yaml
cloudbuild-e2e-cloud-run.yaml
cloudbuild-e2e-gae.yaml
cloudbuild-e2e-gce.yaml
cloudbuild-e2e-gke.yaml
cloudbuild-e2e-image.yaml
cloudbuild-e2e-local.yaml
e2e-test-server/wait-for-image.sh

- Push images to GAR
- Upgrading to latest test runner docker image which lives in GAR
- Update `wait-for-image.sh` and build scripts that were coupled to gcr.

Migrate e2e tests Container Registry usage to Artifact Registry

---

detectors/resources-support/src/main/java/com/google/cloud/opentelemetry/detection/AttributeKeys.java
detectors/resources-support/src/main/java/com/google/cloud/opentelemetry/detection/GCPPlatformDetector.java
detectors/resources-support/src/main/java/com/google/cloud/opentelemetry/detection/GoogleCloudRunJob.java
detectors/resources-support/src/test/java/com/google/cloud/opentelemetry/detection/GCPPlatformDetectorTest.java
examples/metrics/src/main/java/com/google/cloud/opentelemetry/example/metrics/MetricsExporterExample.java

Adds support for detecting Cloud Run Jobs environment.
- Added unit tests pass + Build work.
- Tested with manually built resource-detection library.
- Debug exporter export output. 
`
INFO: metric: ImmutableMetricData{resource=Resource{schemaUrl=null, attributes={cloud.account.id="otel-test", cloud.platform="gcp_cloud_run", cloud.provider="gcp", cloud.region="us-central1", faas.instance="003fb3e0c8b947e4481e1e7e76dc3c594af483befe470a0bbb6fff27f96fa9caa77e6e202dcea43a646942", faas.name="job-metrics-export", gcp.cloud_run.job.execution="job-metrics-export-sprng", gcp.cloud_run.job.task_index=0}}, instrumentationScopeInfo=InstrumentationScopeInfo{name=instrumentation-library-name, version=semver:1.0.0, schemaUrl=null, attributes={}}, name=example_counter, description=Processed jobs, unit=1, …

Support cloud run jobs in resource detection

---

examples/instrumentation-quickstart/src/main/resources/log4j2.xml

Part of https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/issues/334
I am leaving https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/issues/334 open until Spring Boot starter's dependency coordinates for Log4j include the additional fields. See discussion on that bug.

Mention that newer Log4j2 versions do not need additional fields

---

examples/autoconf/build.gradle
examples/autoinstrument/build.gradle
examples/metrics/build.gradle
examples/otlp-spring/build.gradle
examples/otlpmetrics-function/build.gradle
examples/otlptrace/build.gradle
examples/resource/build.gradle
examples/spring-sleuth/README.md
examples/spring-sleuth/build.gradle
examples/spring/build.gradle

This PR hard-codes version number on all samples since they are not meant to be published on maven. 
Hardcoding samples simplifies writing docs and instructions as it gives us deterministic file names from the build output.
Also removes `group` declaration on a few example modules to keep things consistent.

Hardcode versions on all samples

---

build.gradle
exporters/metrics/src/test/java/com/google/cloud/opentelemetry/metric/GoogleCloudMetricExporterTest.java
exporters/metrics/src/test/java/com/google/cloud/opentelemetry/metric/MetricConfigurationTest.java
exporters/trace/src/test/java/com/google/cloud/opentelemetry/trace/TraceConfigurationTest.java
exporters/trace/src/test/java/com/google/cloud/opentelemetry/trace/TraceExporterTest.java

Mockito 3.5.x is incompatible when building with Java 17, therefore an update to a more recent version of Mockito is required. There have been breaking changes in Mockito's releases which are difficult to point out. Some tests required code changes to make them compatible with these changes.
Only breaking change that affected this codebase was the handling of static mocks.
This change only makes the project compatible with Java 17. 
- Minimum Java version required to build is Java 11.
- Artifacts produced are still Java 8 compatible, unless otherwise stated.
Mockito 3.x is also ~5 yrs old at this point.

Make project compatible with Java 17

---

examples/instrumentation-quickstart/docker-compose.yaml
examples/instrumentation-quickstart/otel-collector-config.yaml

Also, update the collector image.  This is the same as https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/pull/364.
Tested by running the quickstart myself and verifying the metrics, traces and logs.

Use exponential histograms in the quickstart sample

---

examples/otlpmetric/README.md
examples/otlpmetric/build.gradle
examples/otlpmetric/src/main/java/com/google/cloud/opentelemetry/example/otlpmetric/OTLPMetricExample.java
examples/otlpmetric/src/main/java/com/google/cloud/opentelemetry/example/otlptrace/OTLPMetricExample.java
settings.gradle

This is a copy of https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/tree/main/examples/otlptrace, but changed to use metrics (based on https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/blob/main/examples/metrics/src/main/java/com/google/cloud/opentelemetry/example/metrics/MetricsExporterExample.java).
TODO: test

Add otlp metric example with gcp auth

---

RELEASING.md

Updates the release instructions to match the current setup.

Fix the error in releasing instructions

---

examples/instrumentation-quickstart/cloudbuild-uninstrumented-app.yaml

Adds a Configuration to allow building uninstrumented version of quickstart sample on Google Cloud Build. The config file is configured to read environment variables and push the built image to Google Artifact Registry.
- Ran `gcloud builds submit --config <(envsubst < cloudbuild-uninstrumented-app.yaml) .` to successfully build and push the image to Google Artifact Registry.

Add GCB config for uninstrumented quickstart

---

examples/otlpmetric/README.md
examples/otlpmetric/build.gradle
examples/otlpmetric/src/main/java/com/google/cloud/opentelemetry/example/otlpmetric/OTLPMetricExample.java
examples/otlptrace/README.md
examples/otlptrace/build.gradle

Updates the OTLP sample with the following changes: 
1. Defers adding quota project header to Google auth library.
2. Adds GCP resource detection.
3. Updates documentation.
4. Shows how to use dynamic headers to enable auto token refresh.
- Manually ran sample with End User Credentials and Service Credentials. 
- Confirmed metrics exported on GCP console.

Update otlpmetrics sample
